<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>EIF</artifactId>
    <version>1.0-SNAPSHOT</version>

    <parent>
        <artifactId>EIF-framework</artifactId>
        <groupId>com.emberinjector</groupId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <repositories>
        <repository>
            <id>local_maven_repo</id>
            <url>file://${project.basedir}/local_maven_repo</url>
        </repository>
    </repositories>

    <packaging>jar</packaging>

    <properties>
        <remapper.mappingFilePath>${project.basedir}/remapper/1.8.9/1.8.9.tiny</remapper.mappingFilePath>
    </properties>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>

                        <configuration>
                            <outputDirectory>${project.basedir}/remapper/libs/1.8.9</outputDirectory>
                            <excludeGroupIds>minecraft.client,com.emberinjector,org.ow2.asm</excludeGroupIds>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.6.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <artifactSet>
                            <includes>
                                <include>com.emberinjector:EIF-commons</include>
                                <include>org.ow2.asm:asm</include>
                                <include>org.ow2.asm:asm-commons</include>
                                <include>org.java-websocket:Java-WebSocket</include>
                                <include>org.slf4j:slf4j-api</include>
                                <include>org.slf4j:slf4j-nop</include>
                            </includes>
                            </artifactSet>
                            <shadedArtifactAttached>true</shadedArtifactAttached>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                            <filters>
                                <filter>
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/MANIFEST.MF</exclude>
                                        <exclude>module-info.class</exclude>
                                    </excludes>
                                </filter>
                            </filters>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.14.0</version>
                <configuration>
                    <annotationProcessors>
                        <annotationProcessor>
                            com.emberinjector.framework.internal.EventHandlerProcessor
                        </annotationProcessor>
                    </annotationProcessors>
                    <compilerArgs>
                        <arg>-Aremapper.mappingFilePath=${remapper.mappingFilePath}</arg>
                        <arg>-Aremapper.sourceNamespace=${remapper.sourceNamespace}</arg>
                        <arg>-Aremapper.destinationNamespace=${remapper.destinationNamespace}</arg>
                    </compilerArgs>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>com.emberinjector</groupId>
            <artifactId>memory-jar-classloader</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.emberinjector</groupId>
            <artifactId>EIF-processor</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.emberinjector</groupId>
            <artifactId>EIF-commons</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.java-websocket</groupId>
            <artifactId>Java-WebSocket</artifactId>
            <version>1.5.3</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.36</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-nop</artifactId>
            <version>1.7.36</version>
        </dependency>
    </dependencies>
</project>