<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>EIF-processor</artifactId>
    <version>1.0-SNAPSHOT</version>

    <packaging>jar</packaging>

    <parent>
        <artifactId>EIF-framework</artifactId>
        <groupId>com.emberinjector</groupId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <repositories>
        <repository>
            <id>fabricmc</id>
            <url>https://maven.fabricmc.net</url>
        </repository>
        <repository>
            <id>local_maven_repo</id>
            <url>file://${project.basedir}/../EIF/local_maven_repo</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>net.fabricmc</groupId>
            <artifactId>mapping-io</artifactId>
            <version>0.7.1</version>
        </dependency>
        <dependency>
            <groupId>net.fabricmc</groupId>
            <artifactId>mapping-io-extras</artifactId>
            <version>0.7.1</version>
        </dependency>
        <dependency>
            <groupId>com.emberinjector</groupId>
            <artifactId>EIF-commons</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
    </dependencies>
</project>